//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarConflict.GameContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MissionsTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MissionsTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarConflict.GameContent.MissionsTexts", typeof(MissionsTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the empire or federation base and fight in the arena..
        /// </summary>
        internal static string StartingNode_ArenaFight_Description {
            get {
                return ResourceManager.GetString("StartingNode_ArenaFight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test your skills in the arena.
        /// </summary>
        internal static string StartingNode_ArenaFight_Name {
            get {
                return ResourceManager.GetString("StartingNode_ArenaFight_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You destoryed the Empire base. Go back to Admiral Kelor claim your reward..
        /// </summary>
        internal static string StartingNode_ClaimKillEmpireReward_Description {
            get {
                return ResourceManager.GetString("StartingNode_ClaimKillEmpireReward_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim your reward from the Federation.
        /// </summary>
        internal static string StartingNode_ClaimKillEmpireReward_Name {
            get {
                return ResourceManager.GetString("StartingNode_ClaimKillEmpireReward_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You destoryed the Federation base. Go back to General Travis claim your reward..
        /// </summary>
        internal static string StartingNode_ClaimKillFederationReward_Description {
            get {
                return ResourceManager.GetString("StartingNode_ClaimKillFederationReward_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim your reward from the Empire.
        /// </summary>
        internal static string StartingNode_ClaimKillFederationReward_Name {
            get {
                return ResourceManager.GetString("StartingNode_ClaimKillFederationReward_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierce is bad for the trading business. 
        ///Solve this problem for the trading guild and they will provide the star drive blueprints..
        /// </summary>
        internal static string StartingNode_DestoryPirateLord_Description {
            get {
                return ResourceManager.GetString("StartingNode_DestoryPirateLord_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy pirate lord Pierce.
        /// </summary>
        internal static string StartingNode_DestoryPirateLord_Name {
            get {
                return ResourceManager.GetString("StartingNode_DestoryPirateLord_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help the Federation destroy one of the Empire bases..
        /// </summary>
        internal static string StartingNode_DestroyEmpire_Description {
            get {
                return ResourceManager.GetString("StartingNode_DestroyEmpire_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy one of the Empire bases.
        /// </summary>
        internal static string StartingNode_DestroyEmpire_Name {
            get {
                return ResourceManager.GetString("StartingNode_DestroyEmpire_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help the Empire destroy the Federation base..
        /// </summary>
        internal static string StartingNode_DestroyFederation_Description {
            get {
                return ResourceManager.GetString("StartingNode_DestroyFederation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroy the Federation base.
        /// </summary>
        internal static string StartingNode_DestroyFederation_Name {
            get {
                return ResourceManager.GetString("StartingNode_DestroyFederation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Epsilon mines and mine 4 diamonds.
        /// </summary>
        internal static string StartingNode_Diamonds_Description {
            get {
                return ResourceManager.GetString("StartingNode_Diamonds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine diamonds.
        /// </summary>
        internal static string StartingNode_Diamonds_Name {
            get {
                return ResourceManager.GetString("StartingNode_Diamonds_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s broken.
        /// </summary>
        internal static string StartingNode_FixCommunication_Description {
            get {
                return ResourceManager.GetString("StartingNode_FixCommunication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the communication system.
        /// </summary>
        internal static string StartingNode_FixCommunication_Name {
            get {
                return ResourceManager.GetString("StartingNode_FixCommunication_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are stuck in this solar system until we fix the warp drive.
        /// </summary>
        internal static string StartingNode_FixWarpDrive_Description {
            get {
                return ResourceManager.GetString("StartingNode_FixWarpDrive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the warp drive.
        /// </summary>
        internal static string StartingNode_FixWarpDrive_Name {
            get {
                return ResourceManager.GetString("StartingNode_FixWarpDrive_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We must get the blueprints to fix our warp drive, or we will be stuck here forever....
        /// </summary>
        internal static string StartingNode_GetWarpDriveBluePrints_Description {
            get {
                return ResourceManager.GetString("StartingNode_GetWarpDriveBluePrints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get warp drive blueprints from the trading guild.
        /// </summary>
        internal static string StartingNode_GetWarpDriveBluePrints_Name {
            get {
                return ResourceManager.GetString("StartingNode_GetWarpDriveBluePrints_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gustav is a shady guy, 
        ///but you will need to meet him to fix the communication system!.
        /// </summary>
        internal static string StartingNode_Gustav_Description {
            get {
                return ResourceManager.GetString("StartingNode_Gustav_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go meet Gustav.
        /// </summary>
        internal static string StartingNode_Gustav_Name {
            get {
                return ResourceManager.GetString("StartingNode_Gustav_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ancient Miner has a mining laser in the mines of sadness.
        /// </summary>
        internal static string StartingNode_MinesOfSadness_Description {
            get {
                return ResourceManager.GetString("StartingNode_MinesOfSadness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the mining laser .
        /// </summary>
        internal static string StartingNode_MinesOfSadness_Name {
            get {
                return ResourceManager.GetString("StartingNode_MinesOfSadness_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk with the Empire before you choose sides..
        /// </summary>
        internal static string StartingNode_VisitEmpire_Description {
            get {
                return ResourceManager.GetString("StartingNode_VisitEmpire_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the Empire planet.
        /// </summary>
        internal static string StartingNode_VisitEmpire_Name {
            get {
                return ResourceManager.GetString("StartingNode_VisitEmpire_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Federation is looking for mercenaries.
        ///Let&apos;s see what they can offer us..
        /// </summary>
        internal static string StartingNode_VisitFederation_Description {
            get {
                return ResourceManager.GetString("StartingNode_VisitFederation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the Federation base.
        /// </summary>
        internal static string StartingNode_VisitFederation_Name {
            get {
                return ResourceManager.GetString("StartingNode_VisitFederation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They can fix our star drive.
        /// </summary>
        internal static string StartingNode_VisitTradingGuild_Description {
            get {
                return ResourceManager.GetString("StartingNode_VisitTradingGuild_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get to the trading guild starbase.
        /// </summary>
        internal static string StartingNode_VisitTradingGuild_Name {
            get {
                return ResourceManager.GetString("StartingNode_VisitTradingGuild_Name", resourceCulture);
            }
        }
    }
}
