//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarConflict.GameContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlotTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolarConflict.GameContent.PlotTexts", typeof(PlotTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MusicTitle {
            get {
                return ResourceManager.GetString("MusicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: .
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Captain Kemron from the Federation starship Vortex.
        ///You are trespassing in a private Federation sector.
        ///Identify yourself!.
        /// </summary>
        internal static string Tutorial10KemronHailing {
            get {
                return ResourceManager.GetString("Tutorial10KemronHailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a servant of the Void. 
        ///Stand aside or face annihilation..
        /// </summary>
        internal static string Tutorial11PlayerRespondKemron1 {
            get {
                return ResourceManager.GetString("Tutorial11PlayerRespondKemron1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My navigation program is experiencing problems. 
        ///I will leave this sector immediately..
        /// </summary>
        internal static string Tutorial12PlayerRespondKemron2 {
            get {
                return ResourceManager.GetString("Tutorial12PlayerRespondKemron2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare for extermination! [Attack].
        /// </summary>
        internal static string Tutorial13PlayerRespondKemron3 {
            get {
                return ResourceManager.GetString("Tutorial13PlayerRespondKemron3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ignore].
        /// </summary>
        internal static string Tutorial14PlayerRespondKemron4 {
            get {
                return ResourceManager.GetString("Tutorial14PlayerRespondKemron4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All hands - battle stations! 
        ///Servant of the Void you are surrounded and outnumbered. 
        ///Lower your shields and prepare to be boarded. 
        ///This is your last warning..
        /// </summary>
        internal static string Tutorial15KemronRespond1 {
            get {
                return ResourceManager.GetString("Tutorial15KemronRespond1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure it does not happen again! 
        ///Your ship signature has been broadcast to all other ships in this sector. 
        ///If you enter again without permission, we will fire immediately. Goodbye..
        /// </summary>
        internal static string Tutorial16KemronRespond2 {
            get {
                return ResourceManager.GetString("Tutorial16KemronRespond2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All hands -  battle stations! [Attack].
        /// </summary>
        internal static string Tutorial17KemronRespond3 {
            get {
                return ResourceManager.GetString("Tutorial17KemronRespond3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain Kemron hailing unidentified ship. 
        ///This is your last warning. 
        ///Identify yourself, or we will disable your ship. .
        /// </summary>
        internal static string Tutorial18KemronRespond4 {
            get {
                return ResourceManager.GetString("Tutorial18KemronRespond4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use #color{255,255,0}Q#defalutColor{} to stun your enemies.
        ///The stun system takes a long time to recharge.
        ///Its remaining cooldown is displayed on the bottom right corner..
        /// </summary>
        internal static string Tutorial19Stun {
            get {
                return ResourceManager.GetString("Tutorial19Stun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper jump completed successfully. 
        ///Initialize briefing protocol. 
        ///Test prototype star destroyer. 
        ///Do not engage other ships unless hostile activity detected. 
        ///Commence test.
        ///(Press space to contiune).
        /// </summary>
        internal static string Tutorial1Awaken {
            get {
                return ResourceManager.GetString("Tutorial1Awaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star destroyer charge complete. #color{255,255,0}Annihilate Sun#defalutColor{}..
        /// </summary>
        internal static string Tutorial20DestroySunVoice {
            get {
                return ResourceManager.GetString("Tutorial20DestroySunVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click #color{255,255,0}1#defalutColor{} to fire star destroyer.
        /// </summary>
        internal static string Tutorial21DestroySunExplanation {
            get {
                return ResourceManager.GetString("Tutorial21DestroySunExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use #ctext{255,255,0,&quot;mouse&quot;} wheel to zoom in and out.
        ///Use #ctext{255,255,0,&quot;WASD&quot;} to move..
        /// </summary>
        internal static string Tutorial2Mouse {
            get {
                return ResourceManager.GetString("Tutorial2Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use mouse wheel to zoom in and out..
        /// </summary>
        internal static string Tutorial3Zoom {
            get {
                return ResourceManager.GetString("Tutorial3Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use left and right mouse buttons to fire the ship guns. .
        /// </summary>
        internal static string Tutorial4Guns {
            get {
                return ResourceManager.GetString("Tutorial4Guns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most asteroids will provide minerals that you can gather.
        ///Minerals are required to upgrade and customize you ship with new weapons, items and ammo. 
        ///Be carefull when destroing red asteroids, they can explode. 
        ///Your ship is fully equipped, you don&apos;t need to gather any minerals now..
        /// </summary>
        internal static string Tutorial5Minerals {
            get {
                return ResourceManager.GetString("Tutorial5Minerals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click E to activate speed boost..
        /// </summary>
        internal static string Tutorial6Speed {
            get {
                return ResourceManager.GetString("Tutorial6Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship is equipped with a Phoenix Device. 
        ///It will be activated automatically when your ship is destroyed.
        ///It will also stun nearby enemies for a few seconds, and push them back..
        /// </summary>
        internal static string Tutorial8PhoenixDevice {
            get {
                return ResourceManager.GetString("Tutorial8PhoenixDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Follow the arrow until you reach the sun. 
        ///The star destroyer will be activated when you are near the sun and not in battle..
        /// </summary>
        internal static string Tutorial9MoveToSun {
            get {
                return ResourceManager.GetString("Tutorial9MoveToSun", resourceCulture);
            }
        }
    }
}
